python src/main_add_obj.py \
    -path robot/G1 \
    -urdf urdf/g1.urdf \
    -srdf urdf/g1.srdf \
    -pkg robot/ \
    -yaml config/g1.yml \
    -smpl smpl \
    -data smpl_data/amass_full_test.pkl \
    -output output/g1_data/full_test \
    -rate 30 \
    -print_joints \
    -add_obj \
    -obj_name ball \
    -obj_urdf /home/wubinghuan/projects/Retarget-devel/Humanoid-Retarget-devel/robot/Ball/Ball.urdf \
    -obj_pkg /home/wubinghuan/projects/Retarget-devel/Humanoid-Retarget-devel/robot/Ball \
    -frame_id head_link