Name: GRMini1T2
Root: pelvis


TPoseJointPositions:
  l_knee_pitch_joint: 25.0
  r_knee_pitch_joint: 25.0
  l_shoulder_roll_joint: 90.0
  r_shoulder_roll_joint: -90.0


ClipMinJointPositions:
  l_knee_pitch_joint: 20.0
  r_knee_pitch_joint: 20.0


ClipMaxJointPositions:
  l_elbow_pitch_joint: 5.0
  r_elbow_pitch_joint: 5.0


SkeletonBinding:
  pelvis: keyframe_pelvis_link
  spine1: keyframe_torso_link
  spine3: keyframe_head_link

  r_collar: keyframe_left_collar_link
  l_collar: keyframe_right_collar_link

  r_shoulder: keyframe_left_shoulder_link
  l_shoulder: keyframe_right_shoulder_link

  r_elbow: keyframe_left_elbow_link
  l_elbow: keyframe_right_elbow_link

  r_wrist: keyframe_left_wrist_link
  l_wrist: keyframe_right_wrist_link

  r_hip: keyframe_left_hip_link
  l_hip: keyframe_right_hip_link

  r_knee: keyframe_left_knee_link
  l_knee: keyframe_right_knee_link

  r_ankle: keyframe_left_ankle_link
  l_ankle: keyframe_right_ankle_link


SkeletonHacking:
  r_ankle: [0.03, 0.0, 0.02]
  l_ankle: [0.03, -0.0, 0.02]

TargetHacking:
  r_elbow: [-0.02, 0.0, 0.02]
  l_elbow: [-0.02, 0.0, 0.02]
  r_wrist: [-0.02, 0.0, 0.02]
  l_wrist: [-0.02, 0.0, 0.02]

FrameTasks:
  pelvis:
    link_name: keyframe_pelvis_link
    pos_smpl_joint: ['pelvis']
    rpy_smpl_joint: ['pelvis']
    axes_rotation: [0., 0., 0.]
    cost:
      position: 0.0
      orientation: 200.0
      damping: 0.0
      gain: 0.1

  head:
    link_name: keyframe_head_link
    pos_smpl_joint: ['spine3']
    rpy_smpl_joint: ['spine3']
    axes_rotation: [0., 0., 0.]
    cost:
      position: 400.0
      orientation: 200.0
      damping: 0.0
      gain: 0.1
  
  left_hip: 
    link_name: keyframe_left_hip_link
    pos_smpl_joint: ['r_hip']
    rpy_smpl_joint: ['r_hip']
    axes_rotation: [0., 0., 0.]
    cost:
      position: 200.0
      orientation: 0.0
      damping: 0.0
      gain: 0.1

  right_hip: 
    link_name: keyframe_right_hip_link
    pos_smpl_joint: ['l_hip']
    rpy_smpl_joint: ['l_hip']
    axes_rotation: [0., 0., 0.]
    cost:
      position: 200.0
      orientation: 0.0
      damping: 0.0
      gain: 0.1

  left_ankle: 
    link_name: keyframe_left_ankle_link
    pos_smpl_joint: ['r_ankle']
    rpy_smpl_joint: ['r_foot']
    axes_rotation: [0., 0., 0.]
    cost:
      position: 1500.0
      orientation: 200.0
      damping: 0.75
      gain: 0.1

  right_ankle: 
    link_name: keyframe_right_ankle_link
    pos_smpl_joint: ['l_ankle']
    rpy_smpl_joint: ['l_foot']
    axes_rotation: [0., 0., 0.]
    cost:
      position: 1500.0
      orientation: 200.0
      damping: 0.75
      gain: 0.1


RelativeFrameTasks:
  left_shoulder:
    link_name: keyframe_left_shoulder_link
    root_name: r_collar
    pos_smpl_joint: ['r_shoulder']
    rpy_smpl_joint: ['r_shoulder']
    axes_rotation: [90., 0., 0.]
    cost:
      position: 0.0
      orientation: 200.0
      damping: 0.75
      gain: 0.1

  right_shoulder:
    link_name: keyframe_right_shoulder_link
    root_name: l_collar
    pos_smpl_joint: ['l_shoulder']
    rpy_smpl_joint: ['l_shoulder']
    axes_rotation: [-90, 0., 0.]
    cost:
      position: 0.0
      orientation: 200.0
      damping: 0.75
      gain: 0.1

  left_elbow:
    link_name: keyframe_left_elbow_link
    root_name: r_collar
    pos_smpl_joint: ['r_elbow']
    rpy_smpl_joint: ['r_elbow']
    axes_rotation: [90., 0., 0.]
    cost:
      position: 0.0
      orientation: 200.0
      damping: 0.75
      gain: 0.1

  right_elbow:
    link_name: keyframe_right_elbow_link
    root_name: l_collar
    pos_smpl_joint: ['l_elbow']
    rpy_smpl_joint: ['l_elbow']
    axes_rotation: [-90, 0., 0.]
    cost:
      position: 0.0
      orientation: 200.0
      damping: 0.75
      gain: 0.1
  
  left_wrist:
    link_name: keyframe_left_wrist_link
    root_name: r_collar
    pos_smpl_joint: ['r_wrist']
    rpy_smpl_joint: ['r_elbow']
    axes_rotation: [90., 0., 0.]
    cost:
      position: 200.0
      orientation: 0.0
      damping: 0.75
      gain: 0.1

  right_wrist:
    link_name: keyframe_right_wrist_link
    root_name: l_collar
    pos_smpl_joint: ['l_wrist']
    rpy_smpl_joint: ['l_elbow']
    axes_rotation: [-90., 0., 0.]
    cost:
      position: 200.0
      orientation: 0.0
      damping: 0.75
      gain: 0.1


CoMTask:
  cost: [50.0, 50.0, 0.0]
  damping: 1.0
  gain: 0.1


AccelerationTask:
  cost: 100.0