python src/main.py \
    -path robot/GRMini1T2 \
    -urdf urdf/grmini1t2.urdf \
    -srdf urdf/grmini1t2.srdf \
    -pkg robot/ \
    -yaml config/grmini1t2.yml \
    -smpl smpl \
    -data smpl_data/amass_full_test.pkl \
    -output output/grmini1t2_data/full_test \
    -rate 30 -print_joints
